; NeoKey WLED Commander
; Platform: Seeed XIAO ESP32-S3 + Adafruit NeoKey 1x4

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit seesaw Library@^1.7.8
    adafruit/Adafruit NeoPixel@^1.12.3
    bblanchon/ArduinoJson@^7.4.1
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -Wall
